# 115.Tuples 4th video - Python tutorial 112
nums = tuple(range(11))
print(nums)
print(type(nums))
nums = list(nums)
print(nums)
print(type(nums))
nums = str(nums)
print(nums)
print(type(nums))